config/routes.rb
Rails.application.routes.draw do

  get 'who_loves_wolfe', to: 'static_pages#who_loves_wolfe'
  get 'order', to: 'static_pages#order'
  resources :buyers, only: :index 
  root 'static_pages#index'

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController

  # GET /buyers
  # GET /buyers.json
  def index
    render json: Buyer.all
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_params
      params.require(:buyer).permit(:avatar, :name, :quantity, :city, :country, :shipped)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def who_loves_wolfe
  end

  def order
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-custom" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <% if controller_name == 'static_pages' && action_name == 'order' %>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag('logo_blue.png', class: 'pull-left') %>
          Wolfe Beer
        <% end %>
      <% else %>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag('logo.png', class: 'pull-left') %>
          Wolfe Beer
        <% end %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Who Loves Wolfe?', who_loves_wolfe_path %>
        </li>
        <li>
          <%= link_to 'Order Now', order_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wolfe RootBeer | The worlds best tasing RootBeer Ever!</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <%= csrf_meta_tags %>
  <%= google_webfonts_init({
    google: ['Lato', 'Raleway']
  }) %>
  
</head>
<body>

<%= render 'layouts/nav' %>

<%= yield %>
	
</body>
</html>

app/views/static_pages/_step1.html.erb
<fieldset id="one" ng-app="app" ng-show="step == 1">
	<div class="form-group">
		<label class="col-sm-2 control-label" for="">Name</label>
		<div class="col-sm-10">
		<input type="text" class="form-control" id="" placeholder="Name">
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-2 control-label" for="">Address</label>
		<div class="col-sm-10">
		<input type="text" class="form-control" id="" placeholder="Shipping Address">
		</div>
	</div>

  <div class="form-group">
    <label class="col-sm-2 control-label" for="textinput">City</label>
    <div class="col-sm-10">
      <input type="text" placeholder="City" class="form-control">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label" for="textinput">State</label>
    <div class="col-sm-4">
      <input type="text" placeholder="State" class="form-control">
    </div>

    <label class="col-sm-2 control-label" for="textinput">Postcode</label>
    <div class="col-sm-4">
      <input type="text" placeholder="Post Code" class="form-control">
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label" for="textinput">Country</label>
    <div class="col-sm-4">
      <input type="text" placeholder="Country" class="form-control">
    </div>

    <label class="col-sm-4 control-label" for="textinput">Quantity of bottles @ $6.99</label>
    <div class="col-sm-2">
      <input type="text" placeholder="Quantity" class="form-control">
    </div>
  </div>

	<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="pull-right">
        <%= link_to 'Cancel', root_path, class: "btn btn-default" %>
        <button class="btn btn-primary" ng-click="nextStep()">Continue</button>
      </div>
    </div>
  </div>
</fieldset>

app/views/static_pages/_step2.html.erb
<div id='two' ng-app"app" ng-show="step == 2">
	<div class="jumbotron">
		<div class="container">
			<h2>Payment Details</h2>
			<p>Credit card or payment details entered here.</p>
		</div>
	</div>
	<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="pull-right">
        <%= link_to 'Cancel', root_path, class: "btn btn-default" %>
        <button class="btn btn-primary" ng-click="nextStep()">Continue</button>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_step3.html.erb
<div id="three" ng-app"app" ng-show="step == 3">
	<div class="jumbotron">
		<div class="container">
			<h2>Confirm your order</h2>
			<p>The details of the order would be reviewed here and then sent to Stripe via the Rails Stripe gem, and create a transaction in the Rails model to record the transaction</p>
		</div>
	</div>
			
	<div class="form-group">
	  <div class="col-sm-offset-2 col-sm-10">
	    <div class="pull-right">
	      <%= link_to 'Cancel', root_path, class: "btn btn-default" %>
	     	<%= link_to 'Checkout', root_path, class: "btn btn-warning" %>
	    </div>
	  </div>
	</div>
</div>

app/views/static_pages/index.html.erb
<header class="intro">
  <div class="intro-body">
    <div class="container">
      <div class="row">
        <div id="branding" class="col-md-8 col-md-offset-2">
          <%= image_tag('icon.png', size: '320') %>
          <p class="intro-text">Small batch, hand crafted, simpley the worlds best root beer ...period.</p>
          <%= link_to 'Order Yours Now', order_path, class: 'btn btn-default btn-lg' %>
        </div>    
      </div>
    </div>
  </div>
</header>

app/views/static_pages/order.html.erb
<div ng-app="app" class="container">
	<div class="row">
		<div id="order" class="col-md-8 col-md-offset-2">
			<div class="text-center">
				<%= image_tag('icon.png', size: '150') %>
			</div>
			<div class="stepwizard">
		    <div class="stepwizard-row setup-panel">
	        <div class="stepwizard-step">
            <a  href="#step-1" type="button" class="btn btn-circle btn-default">1</a>
            <p>Step 1</p>
	        </div>
	        <div  class="stepwizard-step">
            <a href="#step-2" type="button" class="btn btn-circle" >2</a>
            <p>Step 2</p>
	        </div>
	        <div class="stepwizard-step">
            <a href="#step-3" type="button" class="btn btn-circle" >3</a>
            <p>Step 3</p>
	        </div>
		    </div>
			</div>
			<form class="form-horizontal" role="form" ng-controller="formCtrl">

				<%= render 'static_pages/step1' %>
				<%= render 'static_pages/step2' %>
				<%= render 'static_pages/step3' %>
			</form>
		</div>
	</div>
</div>
<footer class="footer-light"></footer>

app/views/static_pages/who_loves_wolfe.html.erb
<header class="intro-2">
  <div class="intro-body">
    <div class="container">
      <h3>Organic all natural ingredients, clean spring water, bottled by elves, and sustainably brewed with unicorn dust...</h3>
    </div>
  </div>
</header>

<div class="container">
	<div id="who-loves" class="row">
		<div class="col-sm-5 col-md-5">
			<div id="stats" class="row">
				<h3>Here's how we're doing</h3>
				<h4>Total Bottles Sold: <span>15,210</span></h4>
				<h4>Total Bottles Shipped: <span>36,632</span></h4>
        <h4>24 oz bottles @ <span>$6.99</span></h4>
				<%= link_to 'Order Yours Now', order_path, class: 'btn btn-default btn-lg' %>
			</div>
			<div id="social" class="row social-icons">
				<h3>Follow Us</h3>
				<ul class="nav navbar-nav navbar-left nav-pills">
          <li><a href="https://twitter.com"><i class="fa fa-twitter-square"></i></a></li>
          <li><a href="https://facebook.com"><i class="fa fa-facebook-official"></i></a></li>
          <li><a href="https://instagram.com"><i class="fa fa-instagram"></i></a></li>
          <li><a href="https://pinterest.com"><i class="fa fa-pinterest-square"></i></a></li>
        </ul>
			</div>
			<div id="instagram" class="row">
				<h3>Instagram</h3>
				<div class="col-md-6 thumb">
          <a class="thumbnail" href="#">
            <%= image_tag('inst1.jpg', size: '200') %>
          </a>
        </div>
        <div class="col-md-6 thumb">
          <a class="thumbnail" href="#">
           	<%= image_tag('inst2.jpg', size: '200') %>
          </a>
        </div>
        <div class="col-md-6 thumb">
          <a class="thumbnail" href="#">
            <%= image_tag('inst3.jpg', size: '200') %>
          </a>
        </div>
        <div class="col-md-6 thumb">
          <a class="thumbnail" href="#">
            <%= image_tag('inst4.jpg', size: '200') %>
          </a>
        </div>
        <div class="col-md-6 thumb">
          <a class="thumbnail" href="#">
            <%= image_tag('inst5.jpg', size: '180') %>
          </a>
        </div>
        <div class="col-md-6 thumb">
          <a class="thumbnail" href="#">
            <%= image_tag('inst6.jpg', size: '180') %>
          </a>
        </div>        
			</div>
		</div>
		<div class="col-sm-6 col-md-6 col-md-offset-1">
			<h3>Who's buying Wolfe Beer?</h3>
				<div ng-app="app" ng-controller="indexCtrl"> 
					<ul class="media-list" ng-repeat="buyer in buyers">
					  <li class="media">
					    <div class="media-left">
					      <a href="#">
					        <img class="media-object img-thumbnail" src="{{buyer.avatar}}" alt="avatar" width="100" height="100">
					      </a>
					    </div>
					    <div class="media-body">
					      <h4 class="media-heading">{{buyer.name}}</h4>
					      <p>{{ buyer.city + ', ' + buyer.country }}<br>
					         {{ buyer.quantity }} bottles ordered!</p>
					    </div>
					  </li>
					</ul>
				</div>
		</div>
	</div>
</div>

<footer>
  <div class="container">
    <p class="navbar-left"><a href="#">Wolfe Beer - The worlds greatest root beer | 2015</a></p>
  </div>
</footer>